services:
  # TODO: build and store the app image to github registry
  application:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ${SECRETS_ENV_FILE:-config/secrets.env}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  postgres:
    build:
      context: ./
      dockerfile: postgres.Dockerfile
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      ES_JAVA_OPTS: "-Xms1024m -Xmx4096m"
    ports:
      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
#      interval: 30s
#      timeout: 60s
#      retries: 5
#      start_period: 80s

volumes:
  postgres_data:
