services:
  application:
    build:
      context: ./
      dockerfile: Dockerfile
    image: grug-discord-bot:local
    restart: unless-stopped
    env_file:
      - ${SECRETS_ENV_FILE:-config/secrets.env}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  postgres:
    build:
      context: ./
      dockerfile: postgres.Dockerfile
    image: grug-discord-bot-postgres:local
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      ES_JAVA_OPTS: "-Xms1024m -Xmx4096m"
    ports:
      - "5432:5432"

  f5tts:
    image: ghcr.io/swivid/f5-tts:main
    runtime: nvidia
    command: f5-tts_infer-gradio --port 7860 --host 0.0.0.0
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - "7860:7860"

volumes:
  postgres_data:
