name: Deploy GitHub Pages
permissions:
  contents: write

on:
  push:
    branches:
      - master
      - main
#    paths:
#      - 'docs/**'
#      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      # https://github.com/astral-sh/setup-uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.24"
          enable-cache: true
      - name: Install Dependencies
        run: uv sync
      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
